<?php
/* This file was generated by the install process. You can edit it. Please see config.original.php to understand the configuration items. */
$cfg = array (
  'web_root' => '',
  'var_root' => '',
  'lang' => '',
  'style' => '',
  'organisation' => '',
  'contactperson' => '',
  'title' => '',
  'preview' => false,
  'enable_crypt' => false,
  'link_name_length' => 8,
  'footerLinks' =>
  array (
    "link1"   =>  "https://link1/",
    "link2"   =>  "https://link2/",
    "Admin"   =>  "admin.php"
  ),
  'upload_password' => 
  array (
  ),
  'upload_ip' => 
  array (
  ),
  'upload_ip_nopassword' => 
  array (
  ),
  'admin_password' => '',
  'admin_http_auth_user' => '',
  'availabilities' => 
  array (
    'minute' => false,
    'hour' => false,
    'day' => false,
    'week' => true,
    'month' => false,
    'quarter' => false,
    'year' => false,
    'none' => false,
  ),
  'availability_default' => 'month',
  'one_time_download' => true,
  'maximal_upload_size' => 0,
  'proxy_ip' => 
  array (
  ),
  'file_hash' => 'md5',
  'litespeed_workaround' => false,
  'store_uploader_ip' => true,
  'installation_done' => true,
  'debug' => false,
  'smtp_host' => '',
  'smtp_port' => 587,
  'smtp_auth' => true,
  'smtp_tls' => true,
  'smtp_user' => '',
  'smtp_pass' => '',
  'sender_email' => '',
  'sender_name' => '',
);
